apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ajaymagar/argoapp:ca522f2adf6f3891a3bdb1fb0a1c61e580896bb8
        ports:
        - containerPort: 3000
