apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ajaymagar/argoapp:e958253a275022d52eaeca0e18455bfcd45bf7a7
        ports:
        - containerPort: 3000
