apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ajaymagar/argoapp:eb687f5c12445104f8ac1c95abd6551b5789dbc0
        ports:
        - containerPort: 3000
