apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ajaymagar/argoapp:ee5a8d48b82626733eb1cdde889a72a9d817cf68
        ports:
        - containerPort: 3000
